site_name: Nya LoCyanFrp! | 文档
theme:
  language: zh
  name: material
  highlightjs: true
  palette:
    - media: "(prefers-color-scheme)"
      primary: pink
      accent: red
      toggle:
        icon: material/brightness-auto
        name: 跟随系统
    - media: "(prefers-color-scheme: light)"
      primary: pink
      accent: red
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: pink
      accent: red
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 暗色模式
  favicon: https://nyalcf.1l1.icu/favicon.ico
  logo: https://nyalcf.1l1.icu/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
#    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.share
    - search.suggest
repo_url: https://github.com/Muska-Ami/NyaLCF
repo_name: GitHub
plugins:
  - tags
  - search
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences